version: '3.1'

services:
  pto-client:
    container_name: pto-client
    build:
      context: ./client/
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
    - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - pto-api
  
  pto-api:
    container_name: pto-api
    build: 
      context: ./api/
    volumes: 
      - ./api:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"

  pto-test:
    container_name: test-runner
    build:
      context: ./client/
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CI=true
    command: npm test
    depends_on: 
      - pto-client
    